version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:dev
    container_name: myapp_dev
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    ports:
      - "9000:9000"

  server:
    image: nginx:alpine
    container_name: myapp_server
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app